### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by varun-affinsys** [Rassibassi/mediapipeDemos#11]
Change model to **"models"**  in the below lines, else people might face Error for "Unable to Load Model"

wget -P model https://rassibassi-mediapipedemos.s3.eu-central-1.amazonaws.com/efficient_face_model.tflite
wget -P model https://rassibassi-mediapipedemos.s3.eu-central-1.amazonaws.com/dlg_model.tflite

**Comment by Rassibassi** [comment]
thanks!
