### ISSUE TITLE
An error caused by passing in an incorrect value

### ISSUE THREAD

**Issue by LingMessy** [Rassibassi/mediapipeDemos#15]
in this file `custom/core.py`
**line 155**
The slice_from_roi function may return a value containing a negative number

resulting in
`custom/iris_lm_depth.py`
**line 22:24**
eye_image.size = 0

The wrong value was passed into the detect_iris function
**line 27:29**
```python
eye_contours, iris_landmarks = detect_iris(
      eye_image.copy(), is_right_eye=is_right_eye
)
```

Causes this part to trigger an error when it runs
**line 52**
```python
eye_frame_low = cv2.resize(
        eye_frame, (side_low, side_low), interpolation=cv2.INTER_AREA
)

# cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4052: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
```

**Comment by LingMessy** [comment]
My English is not very good, some of the content is also translated, maybe the expression is not very clear, sorry

**Comment by Rassibassi** [comment]
Hi,

your english is just fine :)

It is because the users head moves out of the picture, you could solve it like this:

```python
def slice_from_roi(roi, image_size, horizontal_side=True):
    if horizontal_side:
        center = roi["x_center"]
        norm_side = roi["width"]
        image_side = image_size[0]
    else:
        center = roi["y_center"]
        norm_side = roi["height"]
        image_side = image_size[1]

    first_id = int((center - norm_side / 2) * image_side)
    second_id = int((center + norm_side / 2) * image_side)

    first_id = min(max(0, first_id), image_side)
    second_id = min(max(0, second_id), image_side)

    return (first_id, second_id)
 ```
but it will cause different issues.

Since this is just a repository with examples and no production level code anyway, I will just keep the code as is rather than trying to catch all eventualities. Hope the snippet above is of help for you.

Best,
Rasmus
