### ISSUE TITLE
tflite file is missing

### ISSUE THREAD

**Issue by anewusername77** [Rassibassi/mediapipeDemos#16]
Thanks for your work!
but I can't find this page: https://github.com/google/mediapipe/raw/master/mediapipe/modules/iris_landmark/iris_landmark.tflite. Where can I download this file?

**Comment by Rassibassi** [comment]
There is one here which should work:

https://github.com/patlevin/face-detection-tflite/blob/main/fdlite/data/iris_landmark.tflite

**Comment by anewusername77** [comment]
thanks!
