### ISSUE TITLE
Question about code construction

### ISSUE THREAD

**Issue by mirror0129** [Rassibassi/mediapipeDemos#21]
Hi, I'm struggling about the pose estimation, for example I want to get only upper_body skeleton, but I'm not familiar with code construction, so I can find the functions to get the landmarks of the pose, then I cant delete the part of lower_body, could u tell me how to do this? I know it's not a professional question, but I really cant make it😭

**Comment by Rassibassi** [comment]
Hi,

Inside the pose.py the landmarks of the pose are extracted as numpy ndarray. Now just take a subset of the these landmarks, meaning a subset of the rows of the ndarray.

If that is too difficult still, you should start with reading about programming in python and then numpy basics.

Best of luck,
Rasmus
