### ISSUE TITLE
Question about head_posture

### ISSUE THREAD

**Issue by JimHeo** [Rassibassi/mediapipeDemos#25]
Hi,
Thanks for the great job!

I'm just wondering about the range of mp_translation_vector XY in head_posture.py.
I want to normalize the range with [0, 1]. (left:0, right:1, bottom:0, top:1)

Thank you :)

**Comment by Rassibassi** [comment]
`mp_translation_vector` is a translation vector in world coordinate system. The origin of that translation vector is dependent on the intrinsic/extrinsic camera calibration. I would project the vector into the camera projection plane and then normalize its values in the range of [0, 1].

In computer vision applications, the projection of a 3D point from the world coordinate system into the image plane of a camera is done by using the camera's intrinsic and extrinsic parameters.

- Intrinsic parameters: These account for the camera's internal characteristics like focal length, skew, and principal point. These parameters are usually represented in a matrix (K) form.

- Extrinsic parameters: These account for the position and orientation of the camera in the world coordinate system. It is usually represented by a rotation matrix (R) and a translation vector (t).

The basic formula for projecting a 3D point (P_world) in the world coordinate system to the image plane (p) is as follows:

p = K * [R|t] * P_world

Here, [R|t] represents the concatenation of rotation and translation matrices, often referred to as the camera pose.

But remember, after this projection, the point on the image plane (p) is actually in homogeneous coordinates, which means it's a 3D vector. To get the 2D coordinates, we need to do a perspective divide by the third coordinate.

Given a translation vector in the world coordinate system (T_world), you want to project it onto the camera image plane and normalize its position to the range [0,1]. Here's how you can achieve this using numpy:

```python
import numpy as np

def project_point(T_world, K, R, t):
    # Concatenate R and t to form the extrinsic matrix [R|t]
    Rt = np.hstack((R, t))

    # Convert T_world to homogeneous coordinates
    T_world_hom = np.append(T_world, 1)  # T_world in homogeneous coordinates

    # Project the point onto the image plane
    p = np.dot(K, np.dot(Rt, T_world_hom))

    # Perform perspective divide to get the pixel coordinates
    p = p[:2] / p[2]

    return p
```

To normalize the pixel coordinates to the range [0,1], you can simply divide by the image dimensions:
```python
def normalize_point(p, image_width, image_height):
    normalized_p = np.zeros(2)
    normalized_p[0] = p[0] / image_width
    normalized_p[1] = p[1] / image_height

    return normalized_p
```

And you can use these two functions as follows:
```python
# Assuming you have the K, R, t, image dimensions and T_world
T_world = np.array([1, 2, 3])  # replace with your actual translation vector

p = project_point(T_world, K, R, t)
normalized_p = normalize_point(p, image_width, image_height)

print("Normalized Point: ", normalized_p)
```

Remember to replace K, R, t, image_width, image_height, and T_world with your actual values.

This will give you the projected and normalized position of the given 3D point on the image plane. Note that this assumes a pinhole camera model and that lens distortion is either absent or has been corrected beforehand.

The `cv2.projectPoints` function in the OpenCV library does exactly this: it projects 3D points to the image plane given the camera's intrinsic and extrinsic parameters.

The function signature is:
```python
cv2.projectPoints(objectPoints, rvec, tvec, cameraMatrix, distCoeffs)
```

Where:

- `objectPoints` are the 3D points in the world coordinate system.
- `rvec` and `tvec` are the rotation and translation vectors respectively which together represent the extrinsic parameters.
- `cameraMatrix` is the camera's intrinsic matrix.
- `distCoeffs` are the camera's distortion coefficients.

This function returns the projected points in the image plane and the Jacobian matrix. If you want to project a single 3D point and then normalize its coordinates, you could do something like this:

```python
import cv2
import numpy as np

# Assume you have camera parameters
camera_matrix = np.array([...])  # Your camera matrix
dist_coeffs = np.array([...])  # Your distortion coefficients
rvec = np.array([...])  # Your rotation vector
tvec = np.array([...])  # Your translation vector

# Assume your 3D point in world coordinates
point_3d = np.array([[...]])  # 3D point as a 2D NumPy array with shape (1, 3)

# Project the point to the image plane
projected_points, _ = cv2.projectPoints(point_3d, rvec, tvec, camera_matrix, dist_coeffs)

# Get the 2D coordinates
projected_point = projected_points[0, 0, :]

# Normalize the coordinates
image_width = ...  # Your image width
image_height = ...  # Your image height
normalized_point = projected_point / np.array([image_width, image_height])

print("Normalized Point: ", normalized_point)
```

In this case, you just need to replace the placeholders (...) with your actual values. This code will give you the projected point in the image plane and normalize its coordinates to the range [0, 1]. Remember that this normalization will only be meaningful if the point lies within the image boundaries (i.e., the projected point's x coordinate is within [0, image_width] and y coordinate is within [0, image_height]).

**Comment by JimHeo** [comment]
Thanks for the detailed explanation to make it easier to understand.
I'll try the method you suggested.

Thank you.
Have a great day.
