### ISSUE TITLE
Reference to understand get_metric_landmarks

### ISSUE THREAD

**Issue by hovnatan** [Rassibassi/mediapipeDemos#3]
Is there a good reference to understand `def get_metric_landmarks(screen_landmarks, pcf)`? I tried reading mediapipe C++ source code, there are many comments on the procedure but I still could not understand how it works. Thanks.

**Comment by hovnatan** [comment]
Thank you! I understand the math part but the steps to the metric landmarks are confusing. What are the `first_iteration_scale`, `second_iteration_scale`, `intermediate_landmarks`?

**Comment by hovnatan** [comment]
Thanks a lot!

**Comment by indradeepc** [comment]
Hi @Rassibassi ,
Can you please shed some light on how to render [canonical face mesh](https://github.com/google/mediapipe/blob/e6c19885c6d3c6f410c730952aeed2852790d306/mediapipe/modules/face_geometry/data/canonical_face_model.obj) as an occluder object into the depth buffer in python. 

As i am rendering a virtual glass but unable to hide the glass arms.

**Comment by Rassibassi** [comment]
I'm sorry, I don't have any experience with that :(
