### ISSUE TITLE
BGR image provided to face_mesh.process

### ISSUE THREAD

**Issue by remmel** [Rassibassi/mediapipeDemos#5]
Thanks for your demo showing how to get world coordinates.
Hovewer I think that you provide to `face_mesh.process` the BGR image instead of RGB
And I remember having seen a difference in some cases (Which would mean that is not simply converted in grayscale)

https://github.com/Rassibassi/mediapipeDemos/blob/f6fd97cd6daab63fbf2d792cd80df030c4dd2651/head_posture.py#L56

You should use `results = face_mesh.process(frame_rgb)` or `results = face_mesh.process(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))`

**Comment by Rassibassi** [comment]
True, nice spotted. I'll correct it when time allows, but feel free to do a PR :)

In `face_mesh.py` it's correct as you suggested. 

https://github.com/Rassibassi/mediapipeDemos/blob/f6fd97cd6daab63fbf2d792cd80df030c4dd2651/face_mesh.py#L19
